name: Publish Docker image

on:
  release:
    types: ["published"]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Log in to Docker Hub
        uses: docker/login-action@3227f5311cb93ffd14d13e65d8cc400d30f4dd8a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Get python package release
        id: version
        run: echo "version=$(uv version --color never --short)" >> "$GITHUB_OUTPUT"

      - name: Check package version used as tag 
        run: echo ${{ steps.version.outputs.version }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@a60f0f62b5c12316066c8db464bfb2faafd7907b
        with:
          images: jmaupetit/md2pdf
          tags: ${{ steps.version.outputs.version }}

      - name: Build and push Docker Debian image
        id: push-debian
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jmaupetit/md2pdf:latest 
            jmaupetit/md2pdf:${{ steps.version.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker Alpine image
        id: push-alpine
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          file: ./Dockerfile.alpine
          push: true
          tags: |
            jmaupetit/md2pdf:alpine
            jmaupetit/md2pdf:${{ steps.version.outputs.version }}-alpine
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation (Debian)
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3
        with:
          subject-name: index.docker.io/jmaupetit/md2pdf
          subject-digest: ${{ steps.push-debian.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation (Alpine)
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3
        with:
          subject-name: index.docker.io/jmaupetit/md2pdf
          subject-digest: ${{ steps.push-alpine.outputs.digest }}
          push-to-registry: true
